filter:
    excluded_paths:
      - vendor/*
      - Tests/Fixtures/*

tools:
    external_code_coverage: true
    php_analyzer:
        enabled: false

checks:
    php:
        code_rating: true
        duplication: true
